import SwiftUI

// Define a SwiftUI view for the introduction screen.
struct IntroductionView: View {
    // State variable to control the visibility of the rocket view.
    @State private var isShowingRocketView = false
    
    var body: some View {
        // Layered view with a gradient background and content on top.
        ZStack {
            // Background gradient from blue to teal, covering the entire safe area.
            LinearGradient(gradient: Gradient(colors: [Color.blue, Color.teal]), startPoint: .top, endPoint: .bottom)
                .edgesIgnoringSafeArea(.all)
            
            // Vertical stack to organize content vertically.
            VStack {
                Spacer() // Pushes content towards the center.
                
                // Display a rocket image with adjustments for size, color, and shadow.
                Image("RocketPilot")
                    .resizable()
                    .aspectRatio(contentMode: .fit)
                    .foregroundColor(.white)
                    .shadow(color: Color.black.opacity(0.3), radius: 5, x: 0, y: 2)
                    .padding(.horizontal, 50)
                    .padding(.bottom, 10)
                
                // Introductory text with styling and padding.
                Text("Design and create your own rocket now!")
                    .font(.title)
                    .fontWeight(.bold)
                    .foregroundColor(.white)
                    .multilineTextAlignment(.center)
                    .padding(.horizontal, 40)
                    .padding(.bottom, 30)
                
                Spacer() // Additional spacer for centering.
                
                // Button to start the rocket creation process.
                Button(action: {
                    // Action to present the rocket view.
                    isShowingRocketView = true
                }) {
                    // Button label with styling.
                    Text("Start")
                        .font(.title)
                        .fontWeight(.bold)
                        .foregroundColor(.black)
                        .frame(width: 200, height: 60)
                        .background(Color.white)
                        .cornerRadius(30)
                        .padding(.horizontal, 50)
                        .padding(.bottom, 30)
                        .shadow(color: Color.black.opacity(0.3), radius: 5, x: 0, y: 2)
                }
                // Present the RocketExplanationView as a full screen cover when the state is true.
                .fullScreenCover(isPresented: $isShowingRocketView) {
                    RocketExplanationView()
                }
                
                // Disclaimer or attribution text for the image used.
                Text("Image generated by Dall-E")
                    .font(.caption)
                    .fontWeight(.light)
                    .foregroundColor(.white.opacity(0.7))
                    .padding(.top, 5)
                    .padding([.horizontal, .bottom], 10)
                    .background(Color.black.opacity(0.5))
                    .cornerRadius(10)
                    .overlay(
                        RoundedRectangle(cornerRadius: 10)
                            .stroke(Color.white.opacity(0.5), lineWidth: 1)
                    )
            }
            .padding() // Padding around the VStack content.
        }
    }
}

// SwiftUI Preview for the IntroductionView.
struct IntroductionView_Previews: PreviewProvider {
    static var previews: some View {
        IntroductionView()
    }
}
